### ISSUE TITLE
Fwd: [Action required] Afrilearn: Update your app to Google Play Billing Library 3 or 4 by Nov 1

### ISSUE THREAD

**Issue by Afrilearn** [mu29/react-native-in-app-purchase#16]
Google rejected my app that uses this package for billing. They want me to use a higher version, please what can be done?

**Comment by mu29** [comment]
Hi! We’ve recently updated the dependencies :) Now it uses [Play Billing Library v4](https://github.com/pedaling/react-native-in-app-purchase/blob/a5889dc21663f67a72753e28ce7a7630a81cb295/android/build.gradle#L29)!
Please update the package version to `@class101/react-native-in-app-purchase@1.0.7`
